# Generated by Django 5.2 on 2026-08-14 17:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acordos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Acordos',
                'verbose_name_plural': 'Acordos',
                'db_table': 'acorodos',
                'db_table_comment': 'Acordos',
                'permissions': (('import_acordos', 'Can import'), ('export_acordos', 'Can export'), ('viewall_acordos', 'Can view all Arquivo do Solfacil Acordo')),
            },
        ),
        migrations.CreateModel(
            name='Carteiras',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Em cadastro'), (2, 'Em validação'), (3, 'Disponivel para Operação'), (4, 'Bloqueda'), (5, 'Cancelada')], db_comment='', default=1, help_text='Situação', verbose_name='Situação')),
                ('nome', models.CharField(db_comment='Nome', help_text='Nome', max_length=150, verbose_name='Nome')),
                ('observacao', models.TextField(db_comment='Observação', help_text='Observação', max_length=3000, verbose_name='Observação')),
                ('nome_cliente_proprietario', models.CharField(db_comment='Nome Cliente Proprietario', help_text='Nome Cliente Proprietario', max_length=150, verbose_name='Nome Cliente Proprietario')),
                ('nome_empresa_responsavel', models.CharField(db_comment='Nome Empresa Responsavel', help_text='Nome Empresa Responsavel', max_length=150, verbose_name='Nome Empresa Responsavel')),
            ],
            options={
                'verbose_name': 'Carteira',
                'verbose_name_plural': 'Carteiras',
                'db_table': 'carteiras',
                'db_table_comment': 'Carteiras',
                'permissions': (('import_carteiras', 'Can import'), ('export_carteiras', 'Can export')),
            },
        ),
        migrations.CreateModel(
            name='Devedores',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(db_comment='Nome do Cliente', help_text='Nome do Cliente', max_length=500, verbose_name='Nome do Cliente')),
                ('cpf_cnpj', models.CharField(db_comment='CPF/CNPJ', db_index=True, help_text='CPF ou CNPJ (com ou sem pontuação).', max_length=300, validators=[django.core.validators.RegexValidator(message='Informe um CPF (xxx.xxx.xxx-xx ou só dígitos) ou um CNPJ (xx.xxx.xxx/xxxx-xx ou só dígitos).', regex='^\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}$|\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}-\\d{2}|\\d{14}')], verbose_name='CPF/CNPJ')),
                ('numero_contrato', models.CharField(db_comment='Numero do Contrato', db_index=True, help_text='Numero do Contrato', max_length=300, verbose_name='Numero do Contrato')),
                ('saldo', models.IntegerField(blank=True, db_comment='Valor do Saldo', help_text='Sem separadores de milhares e sem vírgula. É obrigatório sempre informar as casas decimais, ainda que seu valor seja “00” Exemplo: 128088 deve ser informado para o número R$ 1280,88', null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Valor do Saldo')),
                ('titulo', models.CharField(db_comment='Titulo', db_index=True, help_text='Titulo', max_length=300, verbose_name='Titulo')),
            ],
            options={
                'verbose_name': 'Devedores',
                'verbose_name_plural': 'Devedores',
                'db_table': 'devedores',
                'db_table_comment': 'Devedores',
                'permissions': (('import_devedores', 'Can import'), ('export_devedores', 'Can export'), ('viewall_devedores', 'Can view all Arquivo do Solfacil Acordo')),
            },
        ),
        migrations.CreateModel(
            name='AcordosPagamentos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(2, 'Estornado'), (3, 'Conciliado'), (1, 'Pendente')], db_comment='1 - A vencer, 2 - Pago, 3 - Quebra', default=1, help_text='Situação', verbose_name='Situação')),
                ('metodo_pagamento', models.IntegerField(choices=[(1, 'Pix'), (2, 'Boleto')], db_comment=' ', default=1, help_text='Metodo de Pagamento', verbose_name='Metodo de Pagamento')),
                ('valor_pago', models.IntegerField(blank=True, db_comment='Valor Pago', help_text='Sem separadores de milhares e sem vírgula. É obrigatório sempre informar as casas decimais, ainda que seu valor seja “00” Exemplo: 128088 deve ser informado para o número R$ 1280,88', null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Valor Pago')),
                ('data_pagamento', models.DateField(blank=True, db_comment='Data do Pagamento: AAAA-MM-DD; A: Ano com 4 caracteres M: Mês com 2 caracteres D: Dia com 2 caracteres', db_index=True, help_text='Data do Pagamento: AAAA-MM-DD; A: Ano com 4 caracteres M: Mês com 2 caracteres D: Dia com 2 caracteres', null=True, verbose_name='Data do Pagamento')),
                ('acordo', models.ForeignKey(help_text='Referência à Acordos', on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='cobranca.acordos')),
            ],
            options={
                'verbose_name': 'Pagamento do Acordo',
                'verbose_name_plural': 'Pagamentos do Acordo',
                'db_table': 'acordos_pagamentos',
                'db_table_comment': 'Pagamentos do Acordo',
                'permissions': (('import_acordospagamentos', 'Can import'), ('export_acordospagamentos', 'Can export')),
            },
        ),
        migrations.CreateModel(
            name='AcordosParcelas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'A vencer'), (2, 'Pago'), (3, 'Quebra'), (4, 'Cancelado')], db_comment='1 - A vencer, 2 - Pago, 3 - Quebra', default=1, help_text='Situação', verbose_name='Situação')),
                ('parcela_inicio', models.IntegerField(blank=True, db_comment='Parcela Inicial', help_text='Parcela Inicial', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Parcela Inicial')),
                ('parcela_final', models.IntegerField(blank=True, db_comment='Parcela Final', help_text='Parcela Final', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Parcela Final')),
                ('valor_apagar', models.IntegerField(blank=True, db_comment='Valor A pagar', help_text='Sem separadores de milhares e sem vírgula. É obrigatório sempre informar as casas decimais, ainda que seu valor seja “00” Exemplo: 128088 deve ser informado para o número R$ 1280,88', null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Valor A pagar')),
                ('valor_pago', models.IntegerField(blank=True, db_comment='Valor Pago', help_text='Sem separadores de milhares e sem vírgula. É obrigatório sempre informar as casas decimais, ainda que seu valor seja “00” Exemplo: 128088 deve ser informado para o número R$ 1280,88', null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Valor Pago')),
                ('saldo', models.IntegerField(blank=True, db_comment='Valor do Saldo', help_text='Sem separadores de milhares e sem vírgula. É obrigatório sempre informar as casas decimais, ainda que seu valor seja “00” Exemplo: 128088 deve ser informado para o número R$ 1280,88', null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Valor do Saldo')),
                ('acordo', models.ForeignKey(help_text='Referência à Acordos', on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='cobranca.acordos')),
            ],
            options={
                'verbose_name': 'Parcela do Acordo',
                'verbose_name_plural': 'Parcelas do Acordo',
                'db_table': 'acordos_parecelas',
                'db_table_comment': 'Parcelas do Acordo',
                'permissions': (('import_devedoresparcelas', 'Can import'), ('export_devedoresoarcelas', 'Can export')),
            },
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranca.carteiras')),
                ('devedor', models.ForeignKey(db_comment='Devedor', help_text='Devedor', on_delete=django.db.models.deletion.PROTECT, to='cobranca.devedores', verbose_name='Devedor')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contratos',
                'db_table_comment': 'Contratos',
                'permissions': (('import_contratos', 'Can import'), ('export_contratos', 'Can export')),
            },
        ),
        migrations.AddField(
            model_name='acordos',
            name='devedor',
            field=models.ForeignKey(blank=True, db_comment='Devedor', help_text='Devedor', null=True, on_delete=django.db.models.deletion.PROTECT, to='cobranca.devedores', verbose_name='Devedor'),
        ),
        migrations.CreateModel(
            name='DevedoresContatos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(choices=[(1, 'Telefone'), (2, 'Whatsapp'), (3, 'Email')], db_comment='1 - A vencer, 2 - Pago, 3 - Quebra', default=4, help_text='Situação', verbose_name='Situação')),
                ('contato', models.CharField(db_comment='Contato', help_text='Contato', max_length=500, verbose_name='Contato')),
                ('observacao', models.TextField(db_comment='Observação', help_text='Observação', max_length=3000, verbose_name='Observação')),
                ('devedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranca.devedores')),
            ],
            options={
                'verbose_name': 'Contato do Devedor',
                'verbose_name_plural': 'Contatos do Devedor',
                'db_table': 'devedores_contatos',
                'db_table_comment': 'Contatos do Devedor',
                'permissions': (('import_devedorescontatos', 'Can import'), ('export_devedorescontatos', 'Can export')),
            },
        ),
        migrations.CreateModel(
            name='DevedoresEnderecos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(db_comment='CEP', db_index=True, help_text='CEP', max_length=300, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(db_comment='Logradouro', help_text='Logradouro', max_length=300, null=True, verbose_name='Logradouro')),
                ('bairro', models.CharField(db_comment='Bairro', help_text='Bairro', max_length=300, null=True, verbose_name='Bairro')),
                ('municipio', models.CharField(db_comment='Municipio', help_text='Municipio', max_length=300, null=True, verbose_name='Municipio')),
                ('latitude', models.CharField(blank=True, db_comment='Latitude', help_text='Latitude', max_length=50, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, db_comment='Longitude', help_text='Longitude', max_length=50, null=True, verbose_name='Longitude')),
                ('devedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranca.devedores')),
            ],
            options={
                'verbose_name': 'Endereço do Devedor',
                'verbose_name_plural': 'Endereços do Devedor',
                'db_table': 'devedores_enderecos',
                'db_table_comment': 'Endereços do Devedor',
                'permissions': (('import_devedoresenderecos', 'Can import'), ('export_devedoresenderecos', 'Can export')),
            },
        ),
        migrations.CreateModel(
            name='DevedoresParecelas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'A vencer'), (2, 'Pago'), (3, 'Quebra'), (4, 'Cancelado')], db_comment='1 - A vencer, 2 - Pago, 3 - Quebra', default=1, help_text='Situação', verbose_name='Situação')),
                ('parcela_inicio', models.IntegerField(blank=True, db_comment='Parcela Inicial', help_text='Parcela Inicial', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Parcela Inicial')),
                ('parcela_final', models.IntegerField(blank=True, db_comment='Parcela Final', help_text='Parcela Final', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Parcela Final')),
                ('valor_apagar', models.IntegerField(blank=True, db_comment='Valor A pagar', help_text='Sem separadores de milhares e sem vírgula. É obrigatório sempre informar as casas decimais, ainda que seu valor seja “00” Exemplo: 128088 deve ser informado para o número R$ 1280,88', null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Valor A pagar')),
                ('valor_pago', models.IntegerField(blank=True, db_comment='Valor Pago', help_text='Sem separadores de milhares e sem vírgula. É obrigatório sempre informar as casas decimais, ainda que seu valor seja “00” Exemplo: 128088 deve ser informado para o número R$ 1280,88', null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Valor Pago')),
                ('saldo', models.IntegerField(blank=True, db_comment='Valor do Saldo', help_text='Sem separadores de milhares e sem vírgula. É obrigatório sempre informar as casas decimais, ainda que seu valor seja “00” Exemplo: 128088 deve ser informado para o número R$ 1280,88', null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Valor do Saldo')),
                ('devedor', models.ForeignKey(help_text='Referência à Devedores', on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='cobranca.devedores')),
            ],
            options={
                'verbose_name': 'Parcela do Devedor',
                'verbose_name_plural': 'Parcelas do Devedor',
                'db_table': 'devedores_parecelas',
                'db_table_comment': 'Parcelas do Devedor',
                'permissions': (('import_devedoresparcelas', 'Can import'), ('export_devedoresoarcelas', 'Can export')),
            },
        ),
        migrations.CreateModel(
            name='Propostas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_inclusao', models.DateField(blank=True, db_comment='Data da Decisão: AAAA-MM-DD; A: Ano com 4 caracteres M: Mês com 2 caracteres D: Dia com 2 caracteres', db_index=True, help_text='Data da Decisão: AAAA-MM-DD; A: Ano com 4 caracteres M: Mês com 2 caracteres D: Dia com 2 caracteres', null=True, verbose_name='Data da Decisão')),
                ('decisao', models.IntegerField(blank=True, choices=[(1, 'Aprovado'), (2, 'Rejeitado')], db_comment='', help_text='Situação', null=True, verbose_name='Situação')),
                ('data_decisao', models.DateField(blank=True, db_comment='Data da Decisão: AAAA-MM-DD; A: Ano com 4 caracteres M: Mês com 2 caracteres D: Dia com 2 caracteres', db_index=True, help_text='Data da Decisão: AAAA-MM-DD; A: Ano com 4 caracteres M: Mês com 2 caracteres D: Dia com 2 caracteres', null=True, verbose_name='Data da Decisão')),
                ('observacao', models.TextField(db_comment='Observação', help_text='Observação', max_length=3000, verbose_name='Observação')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranca.contratos')),
                ('usuario_decisao', models.ForeignKey(blank=True, db_comment='Decisor', help_text='Decisor', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Decisor')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'db_table': 'propostas',
                'db_table_comment': 'Propostas',
                'permissions': (('import_propostas', 'Can import'), ('export_propostas', 'Can export')),
            },
        ),
    ]
