# Generated by Django 5.2 on 2025-09-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SebraeParceiro',
            fields=[
                ('cgc_cpf', models.CharField(help_text='Número do CGC ou CPF.', max_length=18, primary_key=True, serialize=False, verbose_name='CGC/CPF')),
                ('account_id', models.CharField(blank=True, help_text='Código único do parceiro no FOCO.', max_length=32, null=True, verbose_name='Código do Parceiro na FOCO')),
                ('cod_parceiro', models.BigIntegerField(blank=True, help_text='Código único do parceiro.', null=True, verbose_name='Código do Parceiro')),
                ('cod_sebrae', models.IntegerField(help_text='Código único do SEBRAE.', verbose_name='Código SEBRAE')),
                ('desc_sebrae', models.CharField(blank=True, help_text='Descrição do SEBRAE.', max_length=255, null=True, verbose_name='Descrição SEBRAE')),
                ('numero', models.CharField(help_text='Número de Contato.', max_length=15, verbose_name='Número de Telefone')),
                ('nome_razao_social', models.CharField(help_text='Nome ou razão social do parceiro.', max_length=255, verbose_name='Nome/Razão Social')),
                ('cod_cid', models.IntegerField(blank=True, help_text='Código do município.', null=True, verbose_name='Código do Município')),
                ('desc_cid', models.CharField(blank=True, help_text='Descrição do município.', max_length=255, null=True, verbose_name='Descrição do Município')),
                ('cod_est', models.IntegerField(blank=True, help_text='Código do estado.', null=True, verbose_name='Código do Estado')),
                ('desc_est', models.CharField(blank=True, help_text='Descrição do estado.', max_length=255, null=True, verbose_name='Descrição do Estado')),
                ('situacao', models.IntegerField(blank=True, help_text='Situação do parceiro.', null=True, verbose_name='Situação')),
                ('deficiencia', models.CharField(blank=True, help_text='Indica se há deficiência (S/N).', max_length=1, null=True, verbose_name='Deficiência')),
                ('sit_cadastral', models.CharField(blank=True, help_text='Situação cadastral do parceiro.', max_length=1, null=True, verbose_name='Situação Cadastral')),
                ('desc_sit_cadastral', models.CharField(blank=True, help_text='Descrição da situação cadastral.', max_length=50, null=True, verbose_name='Descrição da Situação Cadastral')),
                ('data_inclusao', models.DateTimeField(help_text='Data em que o registro foi incluído.', verbose_name='Data de Inclusão')),
                ('data_ultima_alteracao', models.DateTimeField(blank=True, help_text='Data da última alteração no registro.', null=True, verbose_name='Data da Última Alteração')),
                ('termo_aceite_lgpd', models.BooleanField(default=False, help_text='Indica se o termo de aceite da LGPD foi aceito.', verbose_name='Termo de Aceite LGPD')),
                ('data_inclusao_termo_aceite_lgpd', models.DateTimeField(blank=True, help_text='Data em que o termo de aceite da LGPD foi incluído.', null=True, verbose_name='Data de Inclusão do Termo de Aceite LGPD')),
                ('cod_sebrae_termo_aceite_lgpd', models.IntegerField(blank=True, help_text='Código do SEBRAE relacionado ao termo de aceite da LGPD.', null=True, verbose_name='Código SEBRAE do Termo de Aceite LGPD')),
                ('desc_sebrae_termo_aceite_lgpd', models.CharField(blank=True, help_text='Descrição do SEBRAE relacionado ao termo de aceite da LGPD.', max_length=255, null=True, verbose_name='Descrição SEBRAE do Termo de Aceite LGPD')),
                ('cod_parceiro_termo_aceite_lgpd', models.BigIntegerField(blank=True, help_text='Código do parceiro relacionado ao termo de aceite da LGPD.', null=True, verbose_name='Código do Parceiro do Termo de Aceite LGPD')),
                ('nome_parceiro_termo_aceite_lgpd', models.CharField(blank=True, help_text='Nome do parceiro relacionado ao termo de aceite da LGPD.', max_length=255, null=True, verbose_name='Nome do Parceiro do Termo de Aceite LGPD')),
                ('importacao_contato_pliq', models.BooleanField(blank=True, default=False, help_text='Indica se a Importação do Contato para a PliQ foi realizado.', null=True, verbose_name='Importação do Contato na PliQ')),
                ('data_inclusao_importacao_pliq', models.DateTimeField(blank=True, help_text='Data em que a Importação do Contato para a PliQ foi incluído.', null=True, verbose_name='Data de Inclusão da Importação do Contato para a PliQ')),
                ('qnt_vezes_importado_para_pliq', models.IntegerField(default=0, help_text='Indica a Quantidade de Vezes que Ocorreu a Importação do Contato para a PliQ.', verbose_name='Quantidade de Vezes que foi Realizado a Importação do Contato na PliQ')),
            ],
            options={
                'verbose_name': 'Parceiro SEBRAE',
                'verbose_name_plural': 'Parceiros SEBRAE',
                'db_table': 'sebrae_parceiro',
                'db_table_comment': 'Tabela que armazena informações sobre parceiros do SEBRAE.',
            },
        ),
    ]
