# Generated by Django 5.2 on 2026-08-12 16:35

import apps.lgpd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgpd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sebraeparceiro',
            name='cgc_cpf',
            field=models.CharField(help_text='Número do CGC ou CPF.', max_length=18, primary_key=True, serialize=False, validators=[apps.lgpd.models.validar_cgc_cpf], verbose_name='CGC/CPF'),
        ),
    ]
